#!/usr/bin/env python2

import argparse

import fantasy

parser = argparse.ArgumentParser(
    description='View your fantasy league rosters and matchups.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('league_label', type=str,
   help='The label of the league. This should correspond to categories in '
        'your config.ini file.')
conf = parser.parse_args()

lgconf = fantasy.find(conf.league_label)
db = fantasy.db()

for team in db.teams(lgconf):
    print '%s %s' % (str(team.id).ljust(3), team.name)

