#!/usr/bin/env python2

import nflgame.live

import fantasy.league

if __name__ == '__main__':
    year, week = nflgame.live.current_year_and_week()
    conn = fantasy.league.Conn()
    conn.update_status('REG', year, week)
